"use client";

import { Check, FileText, Image as ImageIcon, Mic, Plus, UploadCloud, WifiOff } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { School } from "../../lib/platform-data";
import { enqueueMutation, listMutations, replayMutations } from "../../lib/offline-queue";
import { apiRead } from "../../lib/use-persistent-state";

type Workspace={profile:unknown[];schools:School[];programs:unknown[];sections:unknown[]};

export default function FieldPage(){
  const [workspace,setWorkspace]=useState<Workspace>({profile:[],schools:[],programs:[],sections:[]});const [member,setMember]=useState({name:"عضوة الفريق",clusterLabel:""});const [ready,setReady]=useState(false);const [online,setOnline]=useState(true);const [sent,setSent]=useState(false);const [queueCount,setQueueCount]=useState(0);const [attachments,setAttachments]=useState<{name:string;kind:"image"|"file"|"audio"}[]>([]);const schools=workspace.schools;
  useEffect(()=>{Promise.all([apiRead("/member/workspace"),apiRead("/auth/me")]).then(([space,account])=>{setWorkspace(space as Workspace);setMember((account as {user:{name:string;clusterLabel:string}}).user);setReady(true)}).catch(()=>{localStorage.removeItem("rasd:token");window.location.replace("/login")})},[]);
  useEffect(()=>{const refresh=async()=>setQueueCount((await listMutations()).length);const sync=async()=>{setOnline(navigator.onLine);await refresh();if(!navigator.onLine)return;try{await replayMutations();const latest=await apiRead("/member/workspace") as Workspace;setWorkspace(latest);await refresh()}catch{setOnline(false)}};sync();window.addEventListener("online",sync);window.addEventListener("offline",sync);window.addEventListener("rasd:queue",refresh);return()=>{window.removeEventListener("online",sync);window.removeEventListener("offline",sync);window.removeEventListener("rasd:queue",refresh)}},[]);
  const sendOrQueue=async(path:string,method:"POST"|"PUT",body:Record<string,unknown>)=>{if(!navigator.onLine){await enqueueMutation({path,method,body});setQueueCount((await listMutations()).length);return false}try{const token=localStorage.getItem("rasd:token");const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000"}/api/v1${path}`,{method,headers:{"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});if(!response.ok)throw new Error();return true}catch{setOnline(false);await enqueueMutation({path,method,body});setQueueCount((await listMutations()).length);return false}};
  const saveSchools=async(next:School[])=>{const nextWorkspace={...workspace,schools:next};setWorkspace(nextWorkspace);return sendOrQueue("/member/workspace","PUT",nextWorkspace as unknown as Record<string,unknown>)};
  const toggle=async(id:string)=>{const next=schools.map(school=>school.id===id?{...school,absence:!school.absence}:school);await saveSchools(next)};
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const schoolId=String(form.get("schoolId")??"");const body={schoolId,type:String(form.get("type")??""),text:String(form.get("text")??""),beneficiaries:Number(form.get("beneficiaries")??0),sessions:Number(form.get("sessions")??0),blockers:String(form.get("blockers")??""),attachments:attachments.map(item=>item.name),source:"mobile"};const visitSaved=await sendOrQueue("/visits","POST",body);const next=schools.map(school=>school.id===schoolId?{...school,visits:school.visits+1}:school);await saveSchools(next);setSent(true);window.setTimeout(()=>setSent(false),3000);if(visitSaved)(event.currentTarget as HTMLFormElement).reset()};
  const addAttachments=(files:FileList|null)=>setAttachments(items=>[...items,...Array.from(files??[]).map(file=>({name:file.name,kind:file.type.startsWith("image/")?"image" as const:file.type.startsWith("audio/")?"audio" as const:"file" as const}))]);
  const done=schools.filter(school=>school.absence).length;const initials=member.name.split(/\s+/).map(part=>part[0]).join("").slice(0,2);
  if(!ready)return <main className="field-page"><div className="workspace-loading">جاري تحميل مهامك…</div></main>;
  return <main className="field-page"><header className="field-top"><div><span>{member.clusterLabel||"ملف العنقود"} · اليوم</span><h1>مهام اليوم</h1></div><Link href="/cluster/today" className="avatar member" aria-label="العودة إلى ملف العنقود">{initials}</Link></header>{(!online||queueCount>0)&&<div className="offline-banner"><WifiOff/><span>{online?`جاري إرسال ${queueCount} تغييرات محفوظة`:`في انتظار الاتصال — ${queueCount} تغييرات`}<small>ستُرسل تلقائياً عند عودة الاتصال.</small></span></div>}<div className="field-content"><section className="card"><div className="card-title-row"><div><h2>تثبيت الغياب</h2><p>{done} من {schools.length} مثبتة</p></div></div>{schools.length?<div className="mobile-absence">{schools.map(school=><div key={school.id}><span>{school.name}</span><button className={school.absence?"on":""} onClick={()=>toggle(school.id)}>{school.absence?"تم":"لم يتم"}</button></div>)}</div>:<div className="empty-state"><b>أضيفي مدارس العنقود من ملفك أولاً</b><Link className="secondary-button" href="/cluster/file">فتح ملف العنقود</Link></div>}</section><form className="card quick-visit" onSubmit={submit}><div><h2>تقرير زيارة سريع</h2><p>تُحفظ الزيارة والمرفقات حتى بدون اتصال.</p></div><label><span>المدرسة</span><select name="schoolId" required defaultValue=""><option value="" disabled>اختاري المدرسة</option>{schools.map(school=><option value={school.id} key={school.id}>{school.name}</option>)}</select></label><div className="activity-chips">{["زيارة صفية","زيارة إشرافية","متابعة خطة","ورشة عمل"].map((type,index)=><label key={type}><input type="radio" name="type" value={type} defaultChecked={index===0}/><span>{type}</span></label>)}</div><textarea name="text" required minLength={10} placeholder="وصف مختصر للزيارة وأبرز الملاحظات…"/><div className="field-numbers"><label><span>عدد المستفيدات</span><input name="beneficiaries" type="number" min="0" defaultValue="0"/></label><label><span>عدد الجلسات</span><input name="sessions" type="number" min="0" defaultValue="1"/></label></div><label><span>المعوقات أو الاحتياج</span><textarea name="blockers" placeholder="اختياري"/></label><div className="attachment-grid">{attachments.map((item,index)=><div key={`${item.name}-${index}`}>{item.kind==="image"?<ImageIcon/>:item.kind==="audio"?<Mic/>:<FileText/>}<span>{item.name}</span></div>)}<label><Plus/><span>إضافة مرفق</span><input hidden type="file" multiple accept="image/*,.pdf,.docx,audio/*" onChange={event=>addAttachments(event.target.files)}/></label></div><button className="primary-button login-submit" disabled={!schools.length}>{sent?<><Check/>رُفع التقرير</>:<><UploadCloud/>رفع التقرير</>}</button></form></div></main>;
}
